[2021-12-09 13:16:45,783] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.connect_to_database manual__2021-12-09T13:15:49.466484+00:00 [queued]>
[2021-12-09 13:16:45,827] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.connect_to_database manual__2021-12-09T13:15:49.466484+00:00 [queued]>
[2021-12-09 13:16:45,828] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-09 13:16:45,829] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-09 13:16:45,829] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-09 13:16:45,881] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): connect_to_database> on 2021-12-09 13:15:49.466484+00:00
[2021-12-09 13:16:45,891] {standard_task_runner.py:52} INFO - Started process 688 to run task
[2021-12-09 13:16:45,898] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'connect_to_database', 'manual__2021-12-09T13:15:49.466484+00:00', '--job-id', '783', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp0pc89pfn', '--error-file', '/tmp/tmprf6d9s_i']
[2021-12-09 13:16:45,900] {standard_task_runner.py:77} INFO - Job 783: Subtask connect_to_database
[2021-12-09 13:16:46,046] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.connect_to_database manual__2021-12-09T13:15:49.466484+00:00 [running]> on host b5fd0372bf6e
[2021-12-09 13:16:46,308] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=connect_to_database
AIRFLOW_CTX_EXECUTION_DATE=2021-12-09T13:15:49.466484+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-09T13:15:49.466484+00:00
[2021-12-09 13:16:48,266] {python.py:152} INFO - Done. Returned value was: None
[2021-12-09 13:16:48,424] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=connect_to_database, execution_date=20211209T131549, start_date=20211209T131645, end_date=20211209T131648
[2021-12-09 13:16:48,598] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-09 13:16:48,778] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
