[2021-12-08 22:11:16,981] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.connect_to_database manual__2021-12-08T22:10:25.650879+00:00 [queued]>
[2021-12-08 22:11:16,997] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.connect_to_database manual__2021-12-08T22:10:25.650879+00:00 [queued]>
[2021-12-08 22:11:16,998] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 22:11:16,998] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-08 22:11:16,999] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 22:11:17,015] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): connect_to_database> on 2021-12-08 22:10:25.650879+00:00
[2021-12-08 22:11:17,022] {standard_task_runner.py:52} INFO - Started process 3022 to run task
[2021-12-08 22:11:17,026] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'connect_to_database', 'manual__2021-12-08T22:10:25.650879+00:00', '--job-id', '522', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpkfiyida9', '--error-file', '/tmp/tmpwc4kvtnh']
[2021-12-08 22:11:17,027] {standard_task_runner.py:77} INFO - Job 522: Subtask connect_to_database
[2021-12-08 22:11:17,078] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.connect_to_database manual__2021-12-08T22:10:25.650879+00:00 [running]> on host b5fd0372bf6e
[2021-12-08 22:11:17,141] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=connect_to_database
AIRFLOW_CTX_EXECUTION_DATE=2021-12-08T22:10:25.650879+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-08T22:10:25.650879+00:00
[2021-12-08 22:11:17,608] {python.py:152} INFO - Done. Returned value was: None
[2021-12-08 22:11:17,635] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=connect_to_database, execution_date=20211208T221025, start_date=20211208T221116, end_date=20211208T221117
[2021-12-08 22:11:17,680] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-08 22:11:17,725] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
