[2021-12-30 00:01:55,452] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.connect_to_database manual__2021-12-30T00:01:18.233472+00:00 [queued]>
[2021-12-30 00:01:55,465] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.connect_to_database manual__2021-12-30T00:01:18.233472+00:00 [queued]>
[2021-12-30 00:01:55,466] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-30 00:01:55,466] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-30 00:01:55,466] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-30 00:01:55,483] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): connect_to_database> on 2021-12-30 00:01:18.233472+00:00
[2021-12-30 00:01:55,490] {standard_task_runner.py:52} INFO - Started process 16179 to run task
[2021-12-30 00:01:55,494] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'connect_to_database', 'manual__2021-12-30T00:01:18.233472+00:00', '--job-id', '1785', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpm6kq61xs', '--error-file', '/tmp/tmp04dkvrw4']
[2021-12-30 00:01:55,496] {standard_task_runner.py:77} INFO - Job 1785: Subtask connect_to_database
[2021-12-30 00:01:55,547] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.connect_to_database manual__2021-12-30T00:01:18.233472+00:00 [running]> on host 218df5ddc363
[2021-12-30 00:01:55,605] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=connect_to_database
AIRFLOW_CTX_EXECUTION_DATE=2021-12-30T00:01:18.233472+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-30T00:01:18.233472+00:00
[2021-12-30 00:01:55,608] {python.py:152} INFO - Done. Returned value was: None
[2021-12-30 00:01:55,622] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=connect_to_database, execution_date=20211230T000118, start_date=20211230T000155, end_date=20211230T000155
[2021-12-30 00:01:55,666] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-30 00:01:55,709] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
