[2021-12-13 12:23:32,189] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.connect_to_database manual__2021-12-13T12:23:21.926604+00:00 [queued]>
[2021-12-13 12:23:32,202] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.connect_to_database manual__2021-12-13T12:23:21.926604+00:00 [queued]>
[2021-12-13 12:23:32,203] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 12:23:32,203] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-13 12:23:32,204] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 12:23:32,218] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): connect_to_database> on 2021-12-13 12:23:21.926604+00:00
[2021-12-13 12:23:32,224] {standard_task_runner.py:52} INFO - Started process 3124 to run task
[2021-12-13 12:23:32,227] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'connect_to_database', 'manual__2021-12-13T12:23:21.926604+00:00', '--job-id', '986', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpuexw_jy4', '--error-file', '/tmp/tmprs7r_98j']
[2021-12-13 12:23:32,229] {standard_task_runner.py:77} INFO - Job 986: Subtask connect_to_database
[2021-12-13 12:23:32,269] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.connect_to_database manual__2021-12-13T12:23:21.926604+00:00 [running]> on host 218df5ddc363
[2021-12-13 12:23:32,317] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=connect_to_database
AIRFLOW_CTX_EXECUTION_DATE=2021-12-13T12:23:21.926604+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-13T12:23:21.926604+00:00
[2021-12-13 12:23:32,489] {logging_mixin.py:109} INFO - You're connected to database
[2021-12-13 12:23:32,570] {logging_mixin.py:109} INFO - Database is created
[2021-12-13 12:23:32,570] {python.py:152} INFO - Done. Returned value was: None
[2021-12-13 12:23:32,586] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=connect_to_database, execution_date=20211213T122321, start_date=20211213T122332, end_date=20211213T122332
[2021-12-13 12:23:32,641] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-13 12:23:32,668] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
