[2021-12-08 23:02:51,795] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.connect_to_database manual__2021-12-08T23:02:40.401711+00:00 [queued]>
[2021-12-08 23:02:51,806] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.connect_to_database manual__2021-12-08T23:02:40.401711+00:00 [queued]>
[2021-12-08 23:02:51,807] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 23:02:51,807] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-08 23:02:51,807] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 23:02:51,823] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): connect_to_database> on 2021-12-08 23:02:40.401711+00:00
[2021-12-08 23:02:51,828] {standard_task_runner.py:52} INFO - Started process 5390 to run task
[2021-12-08 23:02:51,832] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'connect_to_database', 'manual__2021-12-08T23:02:40.401711+00:00', '--job-id', '575', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpcwibmr3d', '--error-file', '/tmp/tmpc4dth3fx']
[2021-12-08 23:02:51,833] {standard_task_runner.py:77} INFO - Job 575: Subtask connect_to_database
[2021-12-08 23:02:51,875] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.connect_to_database manual__2021-12-08T23:02:40.401711+00:00 [running]> on host b5fd0372bf6e
[2021-12-08 23:02:51,927] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=connect_to_database
AIRFLOW_CTX_EXECUTION_DATE=2021-12-08T23:02:40.401711+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-08T23:02:40.401711+00:00
[2021-12-08 23:02:52,193] {python.py:152} INFO - Done. Returned value was: None
[2021-12-08 23:02:52,214] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=connect_to_database, execution_date=20211208T230240, start_date=20211208T230251, end_date=20211208T230252
[2021-12-08 23:02:52,247] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-08 23:02:52,301] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
