[2022-01-02 18:38:09,184] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.pre_process_print_cycle manual__2022-01-02T18:37:22.208141+00:00 [queued]>
[2022-01-02 18:38:09,210] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.pre_process_print_cycle manual__2022-01-02T18:37:22.208141+00:00 [queued]>
[2022-01-02 18:38:09,211] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-02 18:38:09,211] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-02 18:38:09,212] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-02 18:38:09,236] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): pre_process_print_cycle> on 2022-01-02 18:37:22.208141+00:00
[2022-01-02 18:38:09,245] {standard_task_runner.py:52} INFO - Started process 11279 to run task
[2022-01-02 18:38:09,253] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'pre_process_print_cycle', 'manual__2022-01-02T18:37:22.208141+00:00', '--job-id', '1840', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpmbgfbw3j', '--error-file', '/tmp/tmp_3q8lrzb']
[2022-01-02 18:38:09,255] {standard_task_runner.py:77} INFO - Job 1840: Subtask pre_process_print_cycle
[2022-01-02 18:38:09,339] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.pre_process_print_cycle manual__2022-01-02T18:37:22.208141+00:00 [running]> on host 218df5ddc363
[2022-01-02 18:38:09,439] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=pre_process_print_cycle
AIRFLOW_CTX_EXECUTION_DATE=2022-01-02T18:37:22.208141+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-02T18:37:22.208141+00:00
[2022-01-02 18:38:09,468] {warnings.py:110} WARNING - /opt/***/dags/tasks_methods.py:13: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  file.columns = file.columns.str.replace('$','')

[2022-01-02 18:38:09,473] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pre_processing_print_cycle.py", line 16, in pre_process_print_cycle
    pre_process(f, saving_folder)
  File "/opt/airflow/dags/tasks_methods.py", line 16, in pre_process
    file.to_csv(os.path.join(saving_folder, file_hash), index=False, sep=';')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/test_data/processing_files/print_cycle/86a0bab0dafacb1d6eedf315488a69d09fcdf9d64a243c2c1c42aa2a07be9050\n'
[2022-01-02 18:38:09,509] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=cpp_workflow, task_id=pre_process_print_cycle, execution_date=20220102T183722, start_date=20220102T183809, end_date=20220102T183809
[2022-01-02 18:38:09,539] {standard_task_runner.py:91} ERROR - Failed to execute job 1840 for task pre_process_print_cycle
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pre_processing_print_cycle.py", line 16, in pre_process_print_cycle
    pre_process(f, saving_folder)
  File "/opt/airflow/dags/tasks_methods.py", line 16, in pre_process
    file.to_csv(os.path.join(saving_folder, file_hash), index=False, sep=';')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/test_data/processing_files/print_cycle/86a0bab0dafacb1d6eedf315488a69d09fcdf9d64a243c2c1c42aa2a07be9050\n'
[2022-01-02 18:38:09,587] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-02 18:38:09,667] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
